%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\ergib\OneDrive\Рабочий стол\our_x.csv
%
% Auto-generated by MATLAB on 10-Oct-2022 16:21:48

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time1", "fielddata"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("C:\Users\ergib\OneDrive\Рабочий стол\our_x.csv", opts);

%% Convert to output type
time1 = tbl.time1;
fielddata = tbl.fielddata;

%% Clear temporary variables
clear opts tbl

%% Plot the values x  

plot(time1, fielddata,time2, fielddata1 );grid on;
title("Lab 5: plot the x and y position of end-effector, y is constant");
xlabel("time");
ylabel("position of end-effector");
legend("x position","y position")
