%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\ergib\OneDrive\Рабочий стол\joint_statesdata.csv
%
% Auto-generated by MATLAB on 10-Oct-2022 15:53:08

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 24);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "fieldheaderseq", "fieldheaderstamp", "fieldheaderframe_id", "fieldname0", "fieldname1", "fieldname2", "fieldname3", "fieldname4", "fieldposition0", "fieldposition1", "fieldposition2", "fieldposition3", "fieldposition4", "fieldvelocity0", "fieldvelocity1", "fieldvelocity2", "fieldvelocity3", "fieldvelocity4", "fieldeffort0", "fieldeffort1", "fieldeffort2", "fieldeffort3", "fieldeffort4"];
opts.VariableTypes = ["double", "double", "double", "string", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "fieldheaderframe_id", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["fieldheaderframe_id", "fieldname0"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["fieldname1", "fieldname2", "fieldname3", "fieldname4"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["fieldname1", "fieldname2", "fieldname3", "fieldname4"], "ThousandsSeparator", ",");

% Import the data
tbl = readtable("C:\Users\ergib\OneDrive\Рабочий стол\joint_statesdata.csv", opts);

%% Convert to output type
time = tbl.time;

fieldposition0 = tbl.fieldposition0;
fieldposition1 = tbl.fieldposition1;
fieldposition2 = tbl.fieldposition2;
fieldposition3 = tbl.fieldposition3;
fieldposition4 = tbl.fieldposition4;

%% Plot the values 

plot(time, fieldposition0,"y-",time, fieldposition1,"b",time, fieldposition2,time, fieldposition3,time, fieldposition4);grid on;
title("Lab 5: plot the /robot/jointstates topic");
xlabel("time");
ylabel("joint states");
legend("end","joint2","joint4","joint6","motortom2m");

%% Clear temporary variables
clear opts tbl